import {
  experienceSections,
  prologueSlides,
  terminology,
  type ExperienceSection,
  type GlossaryTerm,
  type PrologueSlide,
} from "./story";

export type Locale = "en" | "fr" | "de" | "ru" | "ja" | "ko" | "zh";

export const localeOptions: Array<{ id: Locale; nativeName: string; short: string }> = [
  { id: "en", nativeName: "English", short: "EN" },
  { id: "fr", nativeName: "Français", short: "FR" },
  { id: "de", nativeName: "Deutsch", short: "DE" },
  { id: "ru", nativeName: "Русский", short: "RU" },
  { id: "ja", nativeName: "日本語", short: "JA" },
  { id: "ko", nativeName: "한국어", short: "KO" },
  { id: "zh", nativeName: "中文", short: "中文" },
];

type UiCopy = {
  interactiveStory: string; prologue: string; perspectives: string; taglineA: string; taglineB: string;
  start: string; settings: string; recap: string; map: string; terminology: string; language: string;
  menu: string; skipIntro: string; tapNext: string; tapChoose: string; choosePerspective: string;
  chooseCharacter: string; chooseDescription: string; playAs: string; male: string; female: string; or: string;
  maleExperience: string; femaleExperience: string; selectCharacter: string; enterExperience: string;
  characterSelect: string; mainMenu: string; threeLenses: string; experienceIntro: string;
  experience: string; topics: string; frameworkReady: string; frameworkNote: string; nextChapter: string; allChapters: string;
  observedPattern: string; ideologyGap: string; ideologySubtitle: string; women: string; men: string; year: string; points: string;
  chartReading: string; chartReconstruction: string; methodology: string; source: string;
  debateLanguage: string; termsIntro: string; journey: string; femaleMap: string; maleMap: string;
  origin: string; originDetail: string; signals: string; signalsDetail: string; perspective: string; perspectiveDetail: string;
  experienceDetail: string; otherPath: string; youAreHere: string; mapHint: string;
  system: string; autoAdvance: string; autoAdvanceDetail: string; reduceMotion: string; reduceMotionDetail: string;
  languageDetail: string; lastPath: string; noJourney: string; resume: string; begin: string; close: string;
};

const ui: Record<Locale, UiCopy> = {
  en: {
    interactiveStory:"an interactive story",prologue:"prologue",perspectives:"two perspectives · one society",taglineA:"Choose a side.",taglineB:"Understand both.",start:"Start",settings:"Settings",recap:"Recap",map:"Map",terminology:"Terminology",language:"Language",menu:"Menu",skipIntro:"Skip intro",tapNext:"Tap or swipe to continue",tapChoose:"Tap to choose your character",choosePerspective:"Your perspective",chooseCharacter:"Choose your character",chooseDescription:"See the same world through a different set of pressures, incentives, and expectations.",playAs:"Play as",male:"Male",female:"Female",or:"or",maleExperience:"the male experience",femaleExperience:"the female experience",selectCharacter:"Select a character",enterExperience:"Enter the {gender} experience",characterSelect:"Character select",mainMenu:"Main menu",threeLenses:"Your three lenses",experienceIntro:"Explore the same three forces from this perspective. Each chapter will grow as new findings and evidence are added.",experience:"experience",topics:"Topics in this chapter",frameworkReady:"Framework ready",frameworkNote:"Interactive scenarios and evidence will live inside this chapter.",nextChapter:"Next chapter",allChapters:"All chapters",observedPattern:"Observed pattern · ages 18–29",ideologyGap:"A widening ideology gap",ideologySubtitle:"Political ideology shown as percentage liberal minus percentage conservative, by sex.",women:"Women",men:"Men",year:"Year",points:"points",chartReading:"Above zero is more liberal; below zero is more conservative. Pink emphasizes women, blue tracks men.",chartReconstruction:"Approximate reconstruction from the supplied Financial Times graphic. Values are digitized visually, not raw survey records.",methodology:"Methodological context",source:"Source",debateLanguage:"Language of the debate",termsIntro:"These labels change across communities. This glossary describes common usage without endorsing the worldview behind it.",journey:"Your journey",femaleMap:"The female path",maleMap:"The male path",origin:"Origin",originDetail:"Begin the journey",signals:"The signals",signalsDetail:"Five changes in society",perspective:"Perspective",perspectiveDetail:"Choose whose path to follow",experienceDetail:"Three lenses on the path",otherPath:"Other path",youAreHere:"You are here",mapHint:"Drag to explore · pinch to zoom · tap a level",system:"System",autoAdvance:"Auto-advance",autoAdvanceDetail:"Move through prologue slides every 3.5 seconds",reduceMotion:"Reduce motion",reduceMotionDetail:"Minimize scene and interface animation",languageDetail:"Change the language across the whole experience",lastPath:"Last path",noJourney:"No journey recorded yet. Start the prologue and choose a character.",resume:"Resume",begin:"Begin",close:"Close"
  },
  fr: {
    interactiveStory:"une histoire interactive",prologue:"prologue",perspectives:"deux perspectives · une société",taglineA:"Choisissez un camp.",taglineB:"Comprenez les deux.",start:"Commencer",settings:"Réglages",recap:"Récapitulatif",map:"Carte",terminology:"Terminologie",language:"Langue",menu:"Menu",skipIntro:"Passer l’intro",tapNext:"Touchez ou balayez pour continuer",tapChoose:"Touchez pour choisir votre personnage",choosePerspective:"Votre perspective",chooseCharacter:"Choisissez votre personnage",chooseDescription:"Voyez le même monde à travers d’autres pressions, incitations et attentes.",playAs:"Incarner",male:"Homme",female:"Femme",or:"ou",maleExperience:"l’expérience masculine",femaleExperience:"l’expérience féminine",selectCharacter:"Choisissez un personnage",enterExperience:"Entrer dans {gender}",characterSelect:"Choix du personnage",mainMenu:"Menu principal",threeLenses:"Vos trois angles",experienceIntro:"Explorez les mêmes trois forces depuis cette perspective. Chaque chapitre s’enrichira de nouvelles observations et preuves.",experience:"expérience",topics:"Thèmes de ce chapitre",frameworkReady:"Cadre prêt",frameworkNote:"Les scénarios interactifs et les preuves seront intégrés à ce chapitre.",nextChapter:"Chapitre suivant",allChapters:"Tous les chapitres",observedPattern:"Tendance observée · 18–29 ans",ideologyGap:"Un fossé idéologique croissant",ideologySubtitle:"Idéologie politique : pourcentage libéral moins pourcentage conservateur, selon le sexe.",women:"Femmes",men:"Hommes",year:"Année",points:"points",chartReading:"Au-dessus de zéro : plus libéral ; en dessous : plus conservateur. Le rose représente les femmes, le bleu les hommes.",chartReconstruction:"Reconstitution approximative du graphique fourni du Financial Times. Les valeurs sont estimées visuellement, pas issues des données brutes.",methodology:"Contexte méthodologique",source:"Source",debateLanguage:"Le vocabulaire du débat",termsIntro:"Ces étiquettes varient selon les communautés. Ce glossaire décrit les usages courants sans cautionner la vision du monde associée.",journey:"Votre parcours",femaleMap:"Le parcours féminin",maleMap:"Le parcours masculin",origin:"Départ",originDetail:"Commencer le parcours",signals:"Les signaux",signalsDetail:"Cinq évolutions sociales",perspective:"Perspective",perspectiveDetail:"Choisir le parcours à suivre",experienceDetail:"Trois angles d’analyse",otherPath:"Autre parcours",youAreHere:"Vous êtes ici",mapHint:"Glissez · pincez pour zoomer · touchez une étape",system:"Système",autoAdvance:"Défilement automatique",autoAdvanceDetail:"Changer de diapositive toutes les 3,5 secondes",reduceMotion:"Réduire les animations",reduceMotionDetail:"Limiter les mouvements de l’interface",languageDetail:"Changer la langue de toute l’expérience",lastPath:"Dernier parcours",noJourney:"Aucun parcours enregistré. Lancez le prologue et choisissez un personnage.",resume:"Reprendre",begin:"Commencer",close:"Fermer"
  },
  de: {
    interactiveStory:"eine interaktive Geschichte",prologue:"Prolog",perspectives:"zwei Perspektiven · eine Gesellschaft",taglineA:"Wähle eine Seite.",taglineB:"Verstehe beide.",start:"Start",settings:"Einstellungen",recap:"Rückblick",map:"Karte",terminology:"Begriffe",language:"Sprache",menu:"Menü",skipIntro:"Intro überspringen",tapNext:"Tippen oder wischen zum Fortfahren",tapChoose:"Tippen, um eine Figur zu wählen",choosePerspective:"Deine Perspektive",chooseCharacter:"Wähle deine Figur",chooseDescription:"Erlebe dieselbe Welt unter anderen Zwängen, Anreizen und Erwartungen.",playAs:"Spielen als",male:"Mann",female:"Frau",or:"oder",maleExperience:"die männliche Erfahrung",femaleExperience:"die weibliche Erfahrung",selectCharacter:"Figur auswählen",enterExperience:"{gender} betreten",characterSelect:"Figurenauswahl",mainMenu:"Hauptmenü",threeLenses:"Deine drei Blickwinkel",experienceIntro:"Betrachte dieselben drei Kräfte aus dieser Perspektive. Jedes Kapitel wächst mit neuen Erkenntnissen und Belegen.",experience:"Erfahrung",topics:"Themen dieses Kapitels",frameworkReady:"Rahmen steht",frameworkNote:"Interaktive Szenarien und Belege werden in dieses Kapitel eingebaut.",nextChapter:"Nächstes Kapitel",allChapters:"Alle Kapitel",observedPattern:"Beobachtetes Muster · 18–29 Jahre",ideologyGap:"Eine wachsende ideologische Kluft",ideologySubtitle:"Politische Ideologie: Anteil liberal minus Anteil konservativ, nach Geschlecht.",women:"Frauen",men:"Männer",year:"Jahr",points:"Punkte",chartReading:"Über null bedeutet liberaler, unter null konservativer. Rosa steht für Frauen, Blau für Männer.",chartReconstruction:"Ungefähre Rekonstruktion der bereitgestellten Financial-Times-Grafik. Die Werte wurden visuell geschätzt und sind keine Rohdaten.",methodology:"Methodischer Kontext",source:"Quelle",debateLanguage:"Sprache der Debatte",termsIntro:"Diese Begriffe variieren je nach Community. Das Glossar beschreibt gängige Verwendungen, ohne die dahinterstehende Weltsicht zu übernehmen.",journey:"Dein Weg",femaleMap:"Der weibliche Weg",maleMap:"Der männliche Weg",origin:"Ursprung",originDetail:"Die Reise beginnen",signals:"Die Signale",signalsDetail:"Fünf gesellschaftliche Veränderungen",perspective:"Perspektive",perspectiveDetail:"Wähle den Weg, dem du folgst",experienceDetail:"Drei Blickwinkel",otherPath:"Anderer Weg",youAreHere:"Du bist hier",mapHint:"Ziehen · mit zwei Fingern zoomen · Etappe antippen",system:"System",autoAdvance:"Automatisch weiter",autoAdvanceDetail:"Alle 3,5 Sekunden zur nächsten Folie",reduceMotion:"Bewegung reduzieren",reduceMotionDetail:"Animationen der Oberfläche minimieren",languageDetail:"Sprache der gesamten Erfahrung ändern",lastPath:"Letzter Weg",noJourney:"Noch kein Weg gespeichert. Starte den Prolog und wähle eine Figur.",resume:"Fortsetzen",begin:"Beginnen",close:"Schließen"
  },
  ru: {
    interactiveStory:"интерактивная история",prologue:"пролог",perspectives:"два взгляда · одно общество",taglineA:"Выберите сторону.",taglineB:"Поймите обе.",start:"Начать",settings:"Настройки",recap:"Итоги",map:"Карта",terminology:"Термины",language:"Язык",menu:"Меню",skipIntro:"Пропустить вступление",tapNext:"Коснитесь или смахните, чтобы продолжить",tapChoose:"Коснитесь, чтобы выбрать персонажа",choosePerspective:"Ваша перспектива",chooseCharacter:"Выберите персонажа",chooseDescription:"Посмотрите на один мир через разные давления, стимулы и ожидания.",playAs:"Играть за",male:"Мужчина",female:"Женщина",or:"или",maleExperience:"мужской опыт",femaleExperience:"женский опыт",selectCharacter:"Выберите персонажа",enterExperience:"Открыть: {gender}",characterSelect:"Выбор персонажа",mainMenu:"Главное меню",threeLenses:"Три ракурса",experienceIntro:"Рассмотрите три силы с этой точки зрения. Главы будут дополняться новыми наблюдениями и данными.",experience:"опыт",topics:"Темы этой главы",frameworkReady:"Каркас готов",frameworkNote:"Здесь появятся интерактивные сценарии и доказательства.",nextChapter:"Следующая глава",allChapters:"Все главы",observedPattern:"Наблюдаемая тенденция · 18–29 лет",ideologyGap:"Растущий идеологический разрыв",ideologySubtitle:"Политическая идеология: доля либералов минус доля консерваторов, по полу.",women:"Женщины",men:"Мужчины",year:"Год",points:"пунктов",chartReading:"Выше нуля — более либерально, ниже — более консервативно. Розовый — женщины, синий — мужчины.",chartReconstruction:"Приблизительное воссоздание предоставленного графика Financial Times. Значения оценены визуально и не являются исходными данными опросов.",methodology:"Методологический контекст",source:"Источник",debateLanguage:"Язык дискуссии",termsIntro:"Значение этих ярлыков меняется от сообщества к сообществу. Словарь описывает употребление, не поддерживая связанную с ним картину мира.",journey:"Ваш путь",femaleMap:"Женский путь",maleMap:"Мужской путь",origin:"Начало",originDetail:"Начать путь",signals:"Сигналы",signalsDetail:"Пять изменений в обществе",perspective:"Перспектива",perspectiveDetail:"Выберите путь",experienceDetail:"Три ракурса",otherPath:"Другой путь",youAreHere:"Вы здесь",mapHint:"Перетаскивайте · масштабируйте жестом · нажмите этап",system:"Система",autoAdvance:"Автопереход",autoAdvanceDetail:"Переключать слайды каждые 3,5 секунды",reduceMotion:"Меньше анимации",reduceMotionDetail:"Свести движение интерфейса к минимуму",languageDetail:"Изменить язык всего приложения",lastPath:"Последний путь",noJourney:"Путь ещё не записан. Запустите пролог и выберите персонажа.",resume:"Продолжить",begin:"Начать",close:"Закрыть"
  },
  ja: {
    interactiveStory:"インタラクティブ・ストーリー",prologue:"プロローグ",perspectives:"2つの視点・1つの社会",taglineA:"立場を選ぶ。",taglineB:"両方を理解する。",start:"スタート",settings:"設定",recap:"振り返り",map:"マップ",terminology:"用語集",language:"言語",menu:"メニュー",skipIntro:"イントロをスキップ",tapNext:"タップまたはスワイプで続ける",tapChoose:"タップしてキャラクターを選ぶ",choosePerspective:"あなたの視点",chooseCharacter:"キャラクターを選ぶ",chooseDescription:"同じ世界を、異なる圧力・動機・期待から見ていきます。",playAs:"選択",male:"男性",female:"女性",or:"または",maleExperience:"男性としての体験",femaleExperience:"女性としての体験",selectCharacter:"キャラクターを選択",enterExperience:"{gender}へ進む",characterSelect:"キャラクター選択",mainMenu:"メインメニュー",threeLenses:"3つの視点",experienceIntro:"同じ3つの力を、この立場から探ります。新しい気づきや根拠に合わせて各章を発展させます。",experience:"の体験",topics:"この章のテーマ",frameworkReady:"枠組みを用意済み",frameworkNote:"インタラクティブな場面と根拠をこの章に追加していきます。",nextChapter:"次の章",allChapters:"すべての章",observedPattern:"観察された傾向・18〜29歳",ideologyGap:"広がる思想の男女差",ideologySubtitle:"政治思想＝リベラルの割合－保守の割合（性別）。",women:"女性",men:"男性",year:"年",points:"ポイント",chartReading:"0より上はリベラル寄り、下は保守寄り。ピンクは女性、青は男性です。",chartReconstruction:"提供されたFinancial Timesの図を概算で再現。値は画像から読み取った推定で、調査の生データではありません。",methodology:"分析方法の補足",source:"出典",debateLanguage:"議論で使われる言葉",termsIntro:"これらの呼び方はコミュニティによって意味が変わります。用語集は、背景の世界観に賛同せず一般的な用法を説明します。",journey:"あなたの道のり",femaleMap:"女性のルート",maleMap:"男性のルート",origin:"出発点",originDetail:"物語を始める",signals:"社会の兆候",signalsDetail:"社会に起きる5つの変化",perspective:"視点",perspectiveDetail:"たどるルートを選ぶ",experienceDetail:"3つの分析視点",otherPath:"別のルート",youAreHere:"現在地",mapHint:"ドラッグ・ピンチで拡大・ステージをタップ",system:"システム",autoAdvance:"自動送り",autoAdvanceDetail:"3.5秒ごとに次のスライドへ",reduceMotion:"動きを減らす",reduceMotionDetail:"画面のアニメーションを抑える",languageDetail:"アプリ全体の言語を変更",lastPath:"前回のルート",noJourney:"まだ記録はありません。プロローグを始め、キャラクターを選んでください。",resume:"再開",begin:"始める",close:"閉じる"
  },
  ko: {
    interactiveStory:"인터랙티브 스토리",prologue:"프롤로그",perspectives:"두 관점 · 하나의 사회",taglineA:"한쪽을 선택하세요.",taglineB:"양쪽을 이해하세요.",start:"시작",settings:"설정",recap:"돌아보기",map:"지도",terminology:"용어",language:"언어",menu:"메뉴",skipIntro:"인트로 건너뛰기",tapNext:"탭하거나 밀어서 계속",tapChoose:"탭하여 캐릭터 선택",choosePerspective:"나의 관점",chooseCharacter:"캐릭터를 선택하세요",chooseDescription:"같은 세상을 서로 다른 압력, 유인, 기대를 통해 바라봅니다.",playAs:"플레이",male:"남성",female:"여성",or:"또는",maleExperience:"남성의 경험",femaleExperience:"여성의 경험",selectCharacter:"캐릭터 선택",enterExperience:"{gender} 시작",characterSelect:"캐릭터 선택",mainMenu:"메인 메뉴",threeLenses:"세 가지 관점",experienceIntro:"같은 세 가지 힘을 이 관점에서 살펴봅니다. 새로운 통찰과 근거가 더해질 때마다 각 장도 발전합니다.",experience:"의 경험",topics:"이 장의 주제",frameworkReady:"구조 준비 완료",frameworkNote:"이 장에 인터랙티브 시나리오와 근거가 추가됩니다.",nextChapter:"다음 장",allChapters:"모든 장",observedPattern:"관찰된 패턴 · 18~29세",ideologyGap:"벌어지는 이념 격차",ideologySubtitle:"정치 이념: 진보 비율에서 보수 비율을 뺀 값, 성별 비교.",women:"여성",men:"남성",year:"연도",points:"포인트",chartReading:"0보다 높으면 진보, 낮으면 보수 성향입니다. 분홍색은 여성, 파란색은 남성입니다.",chartReconstruction:"제공된 Financial Times 그래프를 근사해 재구성했습니다. 값은 이미지에서 추정했으며 원자료가 아닙니다.",methodology:"방법론 맥락",source:"출처",debateLanguage:"논쟁의 언어",termsIntro:"이 명칭들의 의미는 커뮤니티마다 다릅니다. 용어집은 그 세계관을 지지하지 않고 일반적 용례를 설명합니다.",journey:"나의 여정",femaleMap:"여성 경로",maleMap:"남성 경로",origin:"출발",originDetail:"여정 시작",signals:"징후",signalsDetail:"사회의 다섯 가지 변화",perspective:"관점",perspectiveDetail:"따라갈 경로 선택",experienceDetail:"세 가지 분석 관점",otherPath:"다른 경로",youAreHere:"현재 위치",mapHint:"드래그 · 핀치 확대 · 단계를 탭하세요",system:"시스템",autoAdvance:"자동 진행",autoAdvanceDetail:"3.5초마다 다음 슬라이드로 이동",reduceMotion:"동작 줄이기",reduceMotionDetail:"화면 애니메이션 최소화",languageDetail:"전체 앱의 언어 변경",lastPath:"마지막 경로",noJourney:"아직 기록된 여정이 없습니다. 프롤로그를 시작하고 캐릭터를 선택하세요.",resume:"계속",begin:"시작",close:"닫기"
  },
  zh: {
    interactiveStory:"互动故事",prologue:"序章",perspectives:"两种视角 · 同一个社会",taglineA:"选择一方。",taglineB:"理解双方。",start:"开始",settings:"设置",recap:"回顾",map:"地图",terminology:"术语",language:"语言",menu:"菜单",skipIntro:"跳过序章",tapNext:"轻触或滑动以继续",tapChoose:"轻触选择角色",choosePerspective:"你的视角",chooseCharacter:"选择你的角色",chooseDescription:"从不同的压力、激励和期待出发，观察同一个世界。",playAs:"扮演",male:"男性",female:"女性",or:"或",maleExperience:"男性体验",femaleExperience:"女性体验",selectCharacter:"选择角色",enterExperience:"进入{gender}",characterSelect:"角色选择",mainMenu:"主菜单",threeLenses:"三个观察角度",experienceIntro:"从这一立场探索同样的三股力量。新的发现和证据会不断充实每一章。",experience:"体验",topics:"本章主题",frameworkReady:"框架已就绪",frameworkNote:"互动情境和证据将被加入本章。",nextChapter:"下一章",allChapters:"全部章节",observedPattern:"观察到的趋势 · 18–29岁",ideologyGap:"不断扩大的意识形态差距",ideologySubtitle:"政治倾向＝自由派比例减去保守派比例，按性别划分。",women:"女性",men:"男性",year:"年份",points:"个百分点",chartReading:"高于零表示更偏自由派，低于零表示更偏保守派。粉色代表女性，蓝色代表男性。",chartReconstruction:"根据所提供的 Financial Times 图表近似重建。数值来自目测估算，并非调查原始数据。",methodology:"方法说明",source:"来源",debateLanguage:"争论中的语言",termsIntro:"这些标签在不同社群中的含义会变化。本术语表仅说明常见用法，不认同其背后的世界观。",journey:"你的旅程",femaleMap:"女性路线",maleMap:"男性路线",origin:"起点",originDetail:"开始旅程",signals:"社会信号",signalsDetail:"社会中的五项变化",perspective:"视角",perspectiveDetail:"选择要走的路线",experienceDetail:"三种分析视角",otherPath:"另一条路线",youAreHere:"你在这里",mapHint:"拖动探索 · 双指缩放 · 轻触关卡",system:"系统",autoAdvance:"自动播放",autoAdvanceDetail:"每3.5秒切换一张幻灯片",reduceMotion:"减少动态效果",reduceMotionDetail:"尽量减少界面动画",languageDetail:"更改整个应用的语言",lastPath:"上次路线",noJourney:"尚未记录旅程。请开始序章并选择角色。",resume:"继续",begin:"开始",close:"关闭"
  }
};

type ContentCopy = { slides: PrologueSlide[]; sections: ExperienceSection[]; terms: GlossaryTerm[] };
type LocalSection = Omit<ExperienceSection, "id" | "number">;
type LocalTerm = Pick<GlossaryTerm, "shortDefinition" | "context">;

const contentText: Record<Exclude<Locale, "en">, { slides: Array<[string, string]>; sections: LocalSection[]; terms: LocalTerm[] }> = {
  fr: {
    slides:[["les hommes se retirent de la société","Les liens sociaux s’effritent."],["les femmes sombrent dans la dépression","Le bien-être est sous pression."],["la natalité diminue","Moins de familles se forment."],["la criminalité augmente","La confiance sociale se fragilise."],["que se passe-t-il ?","Pour comprendre le conflit, choisissez une perspective."]],
    sections:[
      {mapLabel:"Sélection",eyebrow:"Partenaires · exigences · attentes",title:"Logique de sélection",description:"Comment l’étendue des choix modifie l’attirance, le filtrage, l’approche, l’engagement et les attentes envers un partenaire.",lenses:["Choix disponibles","Critères de sélection","Engagement"],prompt:{male:"Qu’est-ce qui détermine quelles femmes les hommes abordent, jugent accessibles et choisissent pour s’engager — et qu’attendent-ils en retour ?",female:"Qu’est-ce qui détermine quels hommes les femmes remarquent, jugent désirables et choisissent pour s’engager — et qu’attendent-elles en retour ?"}},
      {mapLabel:"Politique",eyebrow:"Vote · priorités · institutions",title:"Logique de vote",description:"Comment les pressions vécues, les incitations, le risque, les valeurs et la confiance institutionnelle façonnent les priorités politiques.",lenses:["Priorités","Risque et sécurité","Confiance institutionnelle"],prompt:{male:"Quelles expériences et incitations donnent aux hommes le sentiment qu’un choix politique protège leurs intérêts ou leur vision de la société ?",female:"Quelles expériences et incitations donnent aux femmes le sentiment qu’un choix politique protège leurs intérêts ou leur vision de la société ?"}},
      {mapLabel:"Valeur et âge",eyebrow:"Âge · regard social · possibilités",title:"Valeur personnelle",description:"Comment l’estime de soi et la valeur sociale ou romantique perçue évoluent au fil de la vie — et pourquoi ces mesures peuvent diverger.",lenses:["Étape de vie","Retour social","Possibilités"],prompt:{male:"Comment l’âge, la santé, les compétences, les relations, les ressources et le statut social modifient-ils la valeur perçue au fil du temps ?",female:"Comment l’âge, la santé, les compétences, les relations, les ressources et le statut social modifient-ils la valeur perçue au fil du temps ?"}}
    ],
    terms:[{shortDefinition:"Étiquette désignant ceux qui rejettent la vision red pill ou acceptent les idées conventionnelles sur les relations entre les sexes.",context:"Il s’agit souvent d’une étiquette imposée plutôt que d’une idéologie cohérente et revendiquée."},{shortDefinition:"Métaphore issue de Matrix signifiant découvrir une vérité cachée ; dans la manosphère, elle désigne souvent l’idée que la société et les rencontres favorisent les femmes.",context:"Le terme est utilisé par des communautés très différentes : le contexte est essentiel."},{shortDefinition:"Version fataliste de la red pill, courante dans les milieux incels, selon laquelle les résultats amoureux seraient déterminés par des traits immuables.",context:"Elle est associée au pessimisme et au désespoir plutôt qu’à une stratégie de changement."}]
  },
  de: {
    slides:[["Männer ziehen sich aus der Gesellschaft zurück","Verbindungen werden schwächer."],["Frauen geraten in Depressionen","Das Wohlbefinden steht unter Druck."],["die Geburtenraten sinken","Weniger Familien entstehen."],["die Kriminalität nimmt zu","Gesellschaftliches Vertrauen schwindet."],["was geschieht hier?","Um den Konflikt zu verstehen, wähle eine Perspektive."]],
    sections:[
      {mapLabel:"Partnerwahl",eyebrow:"Partner · Ansprüche · Erwartungen",title:"Auswahllogik",description:"Wie die Größe des Angebots Anziehung, Filter, Annäherung, Bindung und Erwartungen an einen Partner verändert.",lenses:["Auswahlmenge","Partnerfilter","Bindung"],prompt:{male:"Was bestimmt, wen Männer ansprechen, für erreichbar halten und als feste Partnerin wählen – und was erwarten sie im Gegenzug?",female:"Was bestimmt, wen Frauen wahrnehmen, attraktiv finden und als festen Partner wählen – und was erwarten sie im Gegenzug?"}},
      {mapLabel:"Politik",eyebrow:"Wahl · Prioritäten · Institutionen",title:"Wahllogik",description:"Wie erlebter Druck, Anreize, Risiken, Werte und Vertrauen in Institutionen politische Prioritäten und Wahlentscheidungen prägen.",lenses:["Prioritäten","Risiko und Sicherheit","Institutionenvertrauen"],prompt:{male:"Welche Erfahrungen und Anreize lassen eine politische Entscheidung als Schutz männlicher Interessen oder Gesellschaftsbilder erscheinen?",female:"Welche Erfahrungen und Anreize lassen eine politische Entscheidung als Schutz weiblicher Interessen oder Gesellschaftsbilder erscheinen?"}},
      {mapLabel:"Wert und Alter",eyebrow:"Alter · Rückmeldung · Chancen",title:"Persönlicher Wert",description:"Wie sich Selbstwert und wahrgenommener sozialer oder romantischer Wert über Lebensphasen verändern – und warum diese Maßstäbe auseinandergehen können.",lenses:["Lebensphase","Soziale Rückmeldung","Chancen"],prompt:{male:"Wie verändern Alter, Gesundheit, Fähigkeiten, Beziehungen, Ressourcen und sozialer Status den wahrgenommenen Wert im Zeitverlauf?",female:"Wie verändern Alter, Gesundheit, Fähigkeiten, Beziehungen, Ressourcen und sozialer Status den wahrgenommenen Wert im Zeitverlauf?"}}
    ],
    terms:[{shortDefinition:"Bezeichnung für Menschen, die die Red-Pill-Sicht ablehnen oder konventionelle Vorstellungen von Geschlecht und Beziehungen akzeptieren.",context:"Meist eine Fremdbezeichnung statt einer einheitlichen, selbst definierten Ideologie."},{shortDefinition:"Eine Matrix-Metapher für das angebliche Erwachen zu einer verborgenen Wahrheit; in der Manosphäre oft die Annahme, Gesellschaft und Dating bevorzugten Frauen.",context:"Der Begriff wird in sehr verschiedenen politischen und digitalen Milieus verwendet; der Kontext zählt."},{shortDefinition:"Fatalistische Erweiterung der Red Pill, besonders in Incel-Räumen: romantische Ergebnisse gelten als durch unveränderliche Merkmale festgelegt.",context:"Sie steht eher für Pessimismus und Hoffnungslosigkeit als für eine Veränderungsstrategie."}]
  },
  ru: {
    slides:[["мужчины уходят из общественной жизни","Социальные связи слабеют."],["женщины всё чаще сталкиваются с депрессией","Психологическое благополучие под давлением."],["рождаемость снижается","Создаётся всё меньше семей."],["преступность растёт","Общественное доверие разрушается."],["что происходит?","Чтобы понять конфликт, выберите точку зрения."]],
    sections:[
      {mapLabel:"Выбор партнёра",eyebrow:"Партнёры · требования · ожидания",title:"Логика выбора",description:"Как масштаб выбора влияет на привлекательность, фильтры, знакомство, готовность к отношениям и ожидания от партнёра.",lenses:["Круг выбора","Фильтры партнёра","Обязательства"],prompt:{male:"Что определяет, к кому мужчины подходят, кого считают доступной партнёршей и с кем готовы строить отношения — и чего ждут взамен?",female:"Что определяет, кого женщины замечают, считают привлекательным и с кем готовы строить отношения — и чего ждут взамен?"}},
      {mapLabel:"Политика",eyebrow:"Выборы · приоритеты · институты",title:"Логика голосования",description:"Как жизненное давление, стимулы, риск, ценности и доверие к институтам формируют политические приоритеты и выбор.",lenses:["Приоритеты","Риск и безопасность","Доверие к институтам"],prompt:{male:"Какие переживания и стимулы заставляют мужчин видеть в политическом выборе защиту своих интересов или представления об обществе?",female:"Какие переживания и стимулы заставляют женщин видеть в политическом выборе защиту своих интересов или представления об обществе?"}},
      {mapLabel:"Ценность и возраст",eyebrow:"Возраст · обратная связь · возможности",title:"Личная ценность",description:"Как самооценка и воспринимаемая социальная или романтическая ценность меняются с возрастом — и почему эти оценки могут расходиться.",lenses:["Этап жизни","Социальная реакция","Возможности"],prompt:{male:"Как возраст, здоровье, навыки, отношения, ресурсы и положение в обществе меняют воспринимаемую ценность со временем?",female:"Как возраст, здоровье, навыки, отношения, ресурсы и положение в обществе меняют воспринимаемую ценность со временем?"}}
    ],
    terms:[{shortDefinition:"Ярлык для тех, кто отвергает взгляды «красной таблетки» или придерживается обычных представлений о гендере и отношениях.",context:"Чаще это внешнее обозначение, а не цельная самоопределённая идеология."},{shortDefinition:"Метафора из «Матрицы» об открытии скрытой истины; в маносфере часто означает убеждение, что общество и рынок знакомств благоприятствуют женщинам.",context:"Термин используют разные политические и сетевые сообщества, поэтому важен контекст."},{shortDefinition:"Фаталистическое развитие «красной таблетки», распространённое среди инцелов: романтический успех считается почти полностью заданным неизменными чертами.",context:"Связано скорее с пессимизмом и безнадёжностью, чем со стратегией изменений."}]
  },
  ja: {
    slides:[["男性が社会から距離を置き始めている","人とのつながりが薄れています。"],["女性のうつ状態が増えている","心の健康が圧迫されています。"],["出生率が低下している","家族をつくる人が減っています。"],["犯罪率が上昇している","社会への信頼が揺らいでいます。"],["いったい何が起きているのか？","対立を理解するため、まず視点を選びます。"]],
    sections:[
      {mapLabel:"パートナー選び",eyebrow:"相手 · 条件 · 期待",title:"選択のロジック",description:"選択肢の広さが、魅力の判断、絞り込み、アプローチ、関係への意思、相手への期待をどう変えるか。",lenses:["選択肢の範囲","相手を選ぶ基準","関係への意思"],prompt:{male:"男性は誰に声をかけ、現実的な相手と考え、関係を築こうとするのか。そこにはどんな期待があるのでしょうか。",female:"女性は誰に気づき、魅力的だと感じ、関係を築こうとするのか。そこにはどんな期待があるのでしょうか。"}},
      {mapLabel:"政治",eyebrow:"投票 · 優先課題 · 制度",title:"投票のロジック",description:"日々の圧力、利害、リスク、価値観、制度への信頼が、政治的な優先順位と投票をどう形づくるか。",lenses:["優先課題","リスクと安心","制度への信頼"],prompt:{male:"どのような経験や利害が、男性にとって自分の利益や社会観を守る政治選択につながるのでしょうか。",female:"どのような経験や利害が、女性にとって自分の利益や社会観を守る政治選択につながるのでしょうか。"}},
      {mapLabel:"価値と年齢",eyebrow:"年齢 · 周囲の評価 · 機会",title:"自分の価値",description:"自己評価や社会的・恋愛的な価値の感じ方が人生の段階でどう変わり、なぜ評価軸が食い違うことがあるのか。",lenses:["人生の段階","周囲からの反応","機会"],prompt:{male:"年齢、健康、能力、人間関係、資源、社会的立場は、時間とともに感じる価値をどう変えるのでしょうか。",female:"年齢、健康、能力、人間関係、資源、社会的立場は、時間とともに感じる価値をどう変えるのでしょうか。"}}
    ],
    terms:[{shortDefinition:"レッドピル的な世界観を退ける人、または性別や恋愛について一般的な考え方を受け入れる人を指す呼び名。",context:"一貫した自己定義の思想というより、外部から貼られるラベルとして使われがちです。"},{shortDefinition:"『マトリックス』に由来する「隠された真実に目覚める」という比喩。マノスフィアでは、社会や恋愛が女性に有利だという主張を受け入れる意味で使われます。",context:"政治やネット上の異なる集団でも使われるため、文脈の確認が必要です。"},{shortDefinition:"レッドピルをさらに宿命論的にした考えで、恋愛の結果は変えられない特徴でほぼ決まるとみなします。",context:"改善策よりも悲観や絶望と結びつくことが多い言葉です。"}]
  },
  ko: {
    slides:[["남성들이 사회에서 물러나고 있다","사람 사이의 연결이 약해지고 있습니다."],["여성들이 우울감에 빠지고 있다","정신적 안녕이 압박받고 있습니다."],["출생률이 떨어지고 있다","가정을 이루는 사람이 줄고 있습니다."],["범죄율이 높아지고 있다","사회적 신뢰가 흔들리고 있습니다."],["무슨 일이 벌어지고 있을까?","갈등을 이해하기 위해 먼저 관점을 선택합니다."]],
    sections:[
      {mapLabel:"파트너 선택",eyebrow:"상대 · 조건 · 기대",title:"선택의 논리",description:"선택지의 크기가 매력 판단, 선별, 접근, 관계에 대한 의지와 상대에게 거는 기대를 어떻게 바꾸는지 살펴봅니다.",lenses:["선택지의 범위","파트너 기준","관계에 대한 의지"],prompt:{male:"남성은 누구에게 다가가고, 현실적인 상대로 여기며, 관계를 약속할까요? 또 무엇을 기대할까요?",female:"여성은 누구를 알아보고, 매력적인 상대로 여기며, 관계를 약속할까요? 또 무엇을 기대할까요?"}},
      {mapLabel:"정치",eyebrow:"투표 · 우선순위 · 제도",title:"투표의 논리",description:"삶의 압력, 유인, 위험, 가치관과 제도에 대한 신뢰가 정치적 우선순위와 선택을 어떻게 만드는지 살펴봅니다.",lenses:["우선순위","위험과 안전","제도 신뢰"],prompt:{male:"어떤 경험과 유인이 남성에게 자신의 이해관계나 사회관을 지키는 정치적 선택으로 느껴지게 할까요?",female:"어떤 경험과 유인이 여성에게 자신의 이해관계나 사회관을 지키는 정치적 선택으로 느껴지게 할까요?"}},
      {mapLabel:"가치와 나이",eyebrow:"나이 · 사회적 반응 · 기회",title:"개인의 가치",description:"자존감과 사회적·연애적 가치에 대한 인식이 생애 단계에 따라 어떻게 바뀌고, 왜 서로 다른 기준이 생기는지 살펴봅니다.",lenses:["생애 단계","사회적 반응","기회"],prompt:{male:"나이, 건강, 역량, 관계, 자원과 사회적 지위는 시간이 흐르며 인식되는 가치를 어떻게 바꿀까요?",female:"나이, 건강, 역량, 관계, 자원과 사회적 지위는 시간이 흐르며 인식되는 가치를 어떻게 바꿀까요?"}}
    ],
    terms:[{shortDefinition:"레드필 세계관을 거부하거나 성별과 관계에 대한 통상적 관점을 받아들이는 사람을 가리키는 명칭입니다.",context:"일관된 자기 정체성이라기보다 외부에서 붙이는 꼬리표로 쓰이는 경우가 많습니다."},{shortDefinition:"영화 《매트릭스》에서 나온 ‘숨겨진 진실을 깨닫는다’는 비유입니다. 남초 온라인 공간에서는 사회와 연애 구조가 여성에게 유리하다는 주장을 받아들이는 뜻으로 자주 쓰입니다.",context:"서로 다른 정치·온라인 집단이 사용하므로 맥락이 중요합니다."},{shortDefinition:"레드필을 숙명론적으로 확장한 관점으로, 연애 결과가 바꾸기 어려운 특성에 의해 거의 결정된다고 봅니다.",context:"변화 전략보다는 비관과 절망에 연결되는 경우가 많습니다."}]
  },
  zh: {
    slides:[["男性正在退出社会生活","人与人的连接正在减弱。"],["女性正陷入抑郁","心理健康承受着压力。"],["出生率正在下降","组建家庭的人越来越少。"],["犯罪率正在上升","社会信任正在瓦解。"],["究竟发生了什么？","要理解这场冲突，请先选择一个视角。"]],
    sections:[
      {mapLabel:"择偶",eyebrow:"伴侣 · 要求 · 期待",title:"选择逻辑",description:"可选对象的数量如何改变吸引力判断、筛选、接近、承诺，以及对伴侣的期待。",lenses:["选择范围","伴侣筛选","关系承诺"],prompt:{male:"哪些因素决定男性会接近谁、把谁视为现实的伴侣并愿意承诺？他们又期待得到什么？",female:"哪些因素决定女性会注意谁、把谁视为理想的伴侣并愿意承诺？她们又期待得到什么？"}},
      {mapLabel:"政治",eyebrow:"投票 · 优先事项 · 制度",title:"投票逻辑",description:"现实压力、利益激励、风险、价值观和对制度的信任，如何塑造政治优先事项和投票选择。",lenses:["优先事项","风险与安全","制度信任"],prompt:{male:"哪些经历和激励会让男性觉得某种政治选择能够保护自身利益或社会观念？",female:"哪些经历和激励会让女性觉得某种政治选择能够保护自身利益或社会观念？"}},
      {mapLabel:"价值与年龄",eyebrow:"年龄 · 社会反馈 · 机会",title:"个人价值",description:"自我价值感，以及被感知的社会或恋爱价值，如何随人生阶段变化；不同衡量标准又为何可能分化。",lenses:["人生阶段","社会反馈","机会"],prompt:{male:"年龄、健康、能力、关系、资源和社会地位，会如何改变一个人随时间被感知的价值？",female:"年龄、健康、能力、关系、资源和社会地位，会如何改变一个人随时间被感知的价值？"}}
    ],
    terms:[{shortDefinition:"用来指代拒绝“红药丸”世界观，或接受传统性别与关系观念的人。",context:"它通常是别人贴上的标签，而不是一种统一、自我定义的意识形态。"},{shortDefinition:"源自《黑客帝国》的比喻，意为看见隐藏的真相；在“男性圈”中常指接受“社会和约会体系偏向女性”的主张。",context:"许多不同的政治和网络社群都会使用这一说法，因此必须结合语境理解。"},{shortDefinition:"“红药丸”的宿命论延伸，常见于非自愿独身者社群，认为恋爱结果主要由无法改变的特征决定。",context:"它更多与悲观和绝望相关，而不是改善处境的策略。"}]
  }
};

const localizedContent: Partial<Record<Locale, ContentCopy>> = Object.fromEntries(
  Object.entries(contentText).map(([locale, text]) => [locale, {
    slides: prologueSlides.map((slide, index) => ({ ...slide, text: text.slides[index][0], note: text.slides[index][1] })),
    sections: experienceSections.map((section, index) => ({ ...section, ...text.sections[index] })),
    terms: terminology.map((term, index) => ({ ...term, ...text.terms[index] })),
  }]),
) as Partial<Record<Locale, ContentCopy>>;

export function getTranslation(locale: Locale) {
  const content = localizedContent[locale] ?? { slides: prologueSlides, sections: experienceSections, terms: terminology };
  return { ui: ui[locale], ...content };
}
